require "th.options"
require "th.keymaps"
require "th.plugins"
require "th.colorscheme"
require "th.cmp"
require "th.lsp"
require "th.telescope"
require "th.treesitter"
require "th.autopairs"
require "th.comment"
require "th.gitsigns"

